import {
  Code,
  Code2,
  BarChart,
  Palette,
  Shield,
  Cloud,
  Smartphone,
  Brain,
  Briefcase,
  Users,
  UsersRound,
  Calendar,
  Award,
  Server,
  Layers,
  Database,
  Layout,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  code: Code,
  'code-2': Code2,
  'bar-chart': BarChart,
  palette: Palette,
  shield: Shield,
  cloud: Cloud,
  smartphone: Smartphone,
  brain: Brain,
  briefcase: Briefcase,
  users: Users,
  'users-round': UsersRound,
  calendar: Calendar,
  award: Award,
  server: Server,
  layers: Layers,
  database: Database,
  layout: Layout,
};
